Import('*')

# clean JSON for training
target = ['#datastore/training/cr-label/sconscript.log',
          '#datastore/training/cr-label/coco_format.json']
source = ['#source/training/update_coco_and_paths.py',
          '#datastore/scrape/cr-label/output.manual.batch3.json'  # annotations data, sensitive to batch number
          ]
env.Python(target, source)

# Construct the arguments for annotations, test, train, configs with absolute paths
annotation_path = env.File('#datastore/training/cr-label/coco_format.json').abspath
train_path = env.File('#datastore/training/cr-label/test-train/train.json').abspath
test_path = env.File('#datastore/training/cr-label/test-train/test.json').abspath
testtrain_data_path = env.File('#datastore/scrape/cr-label').abspath
config_path = env.File('#source/training/configs/prima/fast_rcnn_R_50_FPN_3x.yaml').abspath
model_path = env.File('#datastore/training/outputs/fast_rcnn_R_50_FPN_3x_batch3_manual/').abspath


# split data into training and test set
target = ['#datastore/training/cr-label/test-train/sconscript.log',
          '#datastore/training/cr-label/test-train/train.json',
          '#datastore/training/cr-label/test-train/test.json']
source = ['#source/training/utils/cocosplit.py']
batch3_files = Glob('#datastore/scrape/cr-label/batch3/*')  # raw data, sensitive to batch number
source.extend(batch3_files)
arguments = f'--split-ratio 0.85 --annotation-path {annotation_path} --train {train_path} --test {test_path}'
command = f'python {source[0]} {arguments}'          
env.Command(target, source, command)

# train model
target = Glob('#datastore/training/outputs/fast_rcnn_R_50_FPN_3x_batch3_manual/*') # model, sensitive to batch number
source = ['#source/training/tools/train_net.py',
          '#datastore/training/cr-label/test-train/train.json',
          '#datastore/training/cr-label/test-train/test.json']
arguments = f'--dataset_name          ocr1 \
    --json_annotation_train {train_path} \
    --image_path_train      {testtrain_data_path}  \
    --json_annotation_val   {test_path} \
    --image_path_val        {testtrain_data_path}  \
    --config-file           {config_path} \
    --resume                \
    OUTPUT_DIR  {model_path} \
    SOLVER.IMS_PER_BATCH 2' 
command = f'python {source[0]} {arguments}'          
env.Command(target, source, command)

# visualize model
target = Glob('#datastore/training/cr-label/test/batch3_manual/*') # inference output, sensitive to batch number
source = ['#source/training/visualize_model_output.py',
          '#datastore/training/outputs/fast_rcnn_R_50_FPN_3x_batch3_manual/config.yaml',
          '#datastore/training/outputs/fast_rcnn_R_50_FPN_3x_batch3_manual/model_final.pth',]
command = f'bash {source[0]}'          
env.Python(target, source)












