Import('*')

target = ['#output/analysis/sconscript.log',
          '#output/analysis/top_speakers.png',
          '#output/analysis/top_speakers.csv']
source = ['#source/analysis/plot.py']
env.Python(target, source)
